[package]
name = "rustgrad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.1"
num-traits = "0.2.19"
ndarray-rand = "0.15.0"
[dependencies.uuid]
uuid = "1.11.0"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]